[program:buyselles-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/awais-koder/WorkStation/projects/buyselles_bundle/buyselles/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasuser=false
killasgroup=true
user=awais-koder
numprocs=2
redirect_stderr=true
stdout_logfile=/home/awais-koder/WorkStation/projects/buyselles_bundle/buyselles/storage/logs/worker-%(program_name)s_%(process_num)02d.log
stopwaitsecs=3600
